### ISSUE TITLE
don't complain if there are comments or empty lines before the YAML frontmatter

### ISSUE THREAD

**Issue by DeathGodBXX** [johnnychen94/DemoCards.jl#43] opened 2020-08-24 08:01 UTC
In demo4.jl,when I want to generate the cover autoly
`# ---`
`# id: demo4`
`# cover: assets/demo4.png`
`# description: plot cameraman`
`# ---`

the content of demo4.jl:
`using Images,TestImages`
`t = testimage("cameraman")`
`#-`
`save("assets/demo4.png",t)`

Somthing is wrong.Before inserting these code,everything is ok.

julia> include("docs/make.jl")
ERROR: LoadError: expected '<document start>' but found YAML.BlockMappingStartToken at nothing
Stacktrace:
 [1] parse_document_start(::YAML.EventStream) at C:\Users\26947\.julia\packages\YAML\e31Qv\src\parser.jl:167
 [2] peek(::YAML.EventStream) at C:\Users\26947\.julia\packages\YAML\e31Qv\src\parser.jl:54
 [3] compose(::YAML.EventStream) at C:\Users\26947\.julia\packages\YAML\e31Qv\src\composer.jl:39
 [4] load(::YAML.TokenStream, ::Nothing) at C:\Users\26947\.julia\packages\YAML\e31Qv\src\YAML.jl:23
 [5] load at C:\Users\26947\.julia\packages\YAML\e31Qv\src\YAML.jl:28 [inlined]
 [6] load at C:\Users\26947\.julia\packages\YAML\e31Qv\src\YAML.jl:71 [inlined] (repeats 2 times)
 [7] parse(::Val{:Julia}, ::DemoCards.JuliaDemoCard) at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\util
s.jl:136
 [8] parse at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\utils.jl:146 [inlined]
 [9] load_config(::DemoCards.JuliaDemoCard, ::String) at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\typ
es\card.jl:41

 [10] DemoCards.JuliaDemoCard(::String) at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\types\julia.jl:67

 [11] democard(::String) at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\types\card.jl:19
 [12] iterate at .\generator.jl:47 [inlined]
 [13] _collect(::Array{String,1}, ::Base.Generator{Array{String,1},typeof(DemoCards.democard)}, ::Base.EltypeUn
 [23] DemoCards.DemoPage(::String) at C:\Users\26947\.julia\packages\DemoCards\XlSmE\src\types\page.jl:100
 [24] makedemos(::String, ::Dict{String,Mustache.MustacheTokens}; root::String, destination::String, src::Strin
g, build::String, branch::String, edit_branch::String, credit::Bool) at C:\Users\26947\.julia\packages\DemoCard
s\XlSmE\src\generate.jl:86
 [25] makedemos(::String, ::Dict{String,Mustache.MustacheTokens}) at C:\Users\26947\.julia\packages\DemoCards\X
lSmE\src\generate.jl:78
 [26] top-level scope at D:\ATOM\atom-x64-windows\Location\Code\MyTestPkg\docs\make.jl:11
 [27] include(::String) at .\client.jl:457
 [28] top-level scope at REPL[2]:1
in expression starting at D:\ATOM\atom-x64-windows\Location\Code\MyTestPkg\docs\make.jl:11

**Comment by johnnychen94** [comment] 2020-08-24 08:06
My best guess is that the YAML frontmatter is not written correctly and YAML.jl complains about it. Perhaps you'll need to take care of leading whitespaces.

It would be helpful if you can share the contents with a gist https://gist.github.com/.

**Comment by DeathGodBXX** [comment] 2020-08-24 08:14
[5] load at C:\Users\26947.julia\packages\YAML\e31Qv\src\YAML.jl:28 [inlined]
[6] load at C:\Users\26947.julia\packages\YAML\e31Qv\src\YAML.jl:71 [inlined] (repeats 2 times)
Is this normal?

**Comment by DeathGodBXX** [comment] 2020-08-24 08:22
solved! Thanks

**Comment by johnnychen94** [comment] 2020-08-24 08:24
would you mind to share the broken example to me? I’m wondering if there’s something I can fix here

Johnny Chen
陈久宁
School of Mathematical Sciences, East China Normal University, Shanghai
华东师范大学数学科学学院
2020年8月24日 +0800 16:22 DeathGodBXX <notifications@github.com>，写道：

**Comment by DeathGodBXX** [comment] 2020-08-24 08:29
How can I share with you?

**Comment by johnnychen94** [comment] 2020-08-24 08:32
you can upload the file as a public github gist and then share the link here

Thanks!

Johnny Chen
陈久宁
School of Mathematical Sciences, East China Normal University, Shanghai
华东师范大学数学科学学院
2020年8月24日 +0800 16:29 DeathGodBXX <notifications@github.com>，写道：

**Comment by DeathGodBXX** [comment] 2020-08-24 08:35
I can't connect [https://gist.github.com/](url)

**Comment by johnnychen94** [comment] 2020-08-24 08:36
https://gist.github.com/mine perhaps.

**Comment by DeathGodBXX** [comment] 2020-08-24 08:37
I can't connect this github gist,when I click.

**Comment by DeathGodBXX** [comment] 2020-08-24 08:39
I can't connect [https://gist.github.com/mine](url) either.

**Comment by johnnychen94** [comment] 2020-08-24 08:39
Ah. I see. Perhaps upload it and submit a PR?

**Comment by DeathGodBXX** [comment] 2020-08-24 08:58
I have submit a PR.

**Comment by johnnychen94** [comment] 2020-09-06 15:20
The part that I can confirm is fixed by #53. I'm not sure what the other part #44 describes.

For the record, I'm closing this and #44 because the issues are not described very clearly. If there are still problems, feel free to reopen a new one.

**Closed by johnnychen94** 2020-09-06 15:20 UTC
Labels: File: julia, Type: bug
